//@version=5
indicator('ADX', shorttitle='ADX', format=format.price, precision=2, timeframe='')
adxlen = input(14, title='ADX Smoothing')
dilen = input(14, title='DI Length')
dirmov(len) =>
    up = ta.change(high)
    down = -ta.change(low)
    plusDM = na(up) ? na : up > down and up > 0 ? up : 0
    minusDM = na(down) ? na : down > up and down > 0 ? down : 0
    truerange = ta.rma(ta.tr, len)
    plus = fixnan(100 * ta.rma(plusDM, len) / truerange)
    minus = fixnan(100 * ta.rma(minusDM, len) / truerange)
    [plus, minus]
adx(dilen, adxlen) =>
    [plus, minus] = dirmov(dilen)
    sum = plus + minus
    adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
    adx
sig = adx(dilen, adxlen)
_histbase = input(title='Base of Line in the sand', defval=0)
plot(sig, color=sig >= 20 ? color.orange : color.silver, title='ADX', linewidth=2, style=plot.style_columns, histbase=_histbase)
_hLine = hline(20, title='Line in the sand', color=color.purple, linestyle=hline.style_solid, linewidth=2, display = display.none)
