//@version=5
//--------------- Built in BB Modified ---------------
indicator(shorttitle="BB", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length = input.int(26, minval=1)
src = input(close, title="Source")
mult = input.float(2.0, minval=0.001, maxval=50, title="StdDev")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input.int(0, "Offset", minval = -500, maxval = 500)
// fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
//--------------- Built in BB Modified ---------------
var existingCondition = 0
condition1 = if upper[0] < upper[1] and lower[0] < lower[1] and basis[0] < basis[1]
    -1
condition2 = if upper[0] > upper[1] and lower[0] > lower[1] and basis[0] > basis[1]
    1
conditionFull = condition1?-1:condition2?1:na

conditionMini = 0
if conditionFull != existingCondition
    conditionMini := conditionFull
    existingCondition := conditionFull
    existingCondition
    

// set conditionFull to show partial bands only when 3 elements point downwards
// p1 = plot(upper, "Upper", color=color.new(color.blue, conditionFull==-1?0:conditionFull==1?0:100), offset = offset, style = plot.style_stepline, linewidth = 4)
// plot(basis, "Basis", color=color.new(color.orange, conditionFull==-1?0:conditionFull==1?0:100), offset = offset, style = plot.style_stepline, linewidth = 4)
// p2 = plot(lower, "Lower", color=color.new(color.blue, conditionFull==-1?0:conditionFull==1?0:100), offset = offset, style = plot.style_stepline, linewidth = 4)
// plotarrow(conditionFull, 'Force', colorup=color.new(color.black, 0), colordown=color.new(color.black, 0), maxheight = 15)

p1 = plot(upper, "Upper", color=color.new(color.blue, 0), offset = offset, style = plot.style_stepline, linewidth = 4,display = display.none)
plot(basis, "Basis", color=color.new(color.orange, 0), offset = offset, style = plot.style_stepline, linewidth = 4,display = display.none)
p2 = plot(lower, "Lower", color=color.new(color.blue, 0), offset = offset, style = plot.style_stepline, linewidth = 4,display = display.none)

plotarrow(conditionFull, 'Force Full', colorup=color.new(color.fuchsia, 0), colordown=color.new(color.fuchsia, 0), maxheight = 15,display = display.none)
plotarrow(conditionMini, 'Force Mini', colorup=color.new(color.yellow, 0), colordown=color.new(color.yellow, 0), maxheight = 15)





